apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  resource.inclusions: |
    - apiGroups:
      - "apps"
      kinds:
      - Deployment
      clusters:
      - "*"
    - apiGroups:
      - "networking"
      kinds:
      - "Ingress"
      clusters:
      - "*"
    - apiGroups:
      - "*"
      kinds:
      - "Service"
      - "Pod"
      - "ConfigMap"
      - "Secret"
      clusters:
      - "*"
