apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - replicationcontrollers/status
  - pods/status
  - pods/log
  verbs:
  - get 
  - list
  - watch

- apiGroups:
  - ""
  resources:
  - configmaps
  - pods 
  - replicationcontrollers
  - replicationcontrollers/scale
  - secrets
  - services
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
   - apps
  resources:
  - deployments
  - deployments/rollback
  - deployments/scale
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch